### ISSUE TITLE
Is `github:DeterminateSystems/zero-to-nix#example` not reproducible?

### ISSUE THREAD

**Issue by l0b0** [DeterminateSystems/zero-to-nix#253]
https://zero-to-nix.com/start/nix-develop says (my emphasis):

> For curl, for example, you should see a strange path like this (_the hash part should be different on your machine_):

Shouldn't the hash part be _identical_ on every machine?

**Comment by lucperkins** [comment]
The hash should be different on each system type (x86_64 Linux vs aarch64 macOS vs etc) because `system` is a required attribute in every Nix derivation. I typically use fake hashes in documentation to make sure not to confuse readers by ensuring that *no one* sees the hash that I get on my own machine.
