### ISSUE TITLE
Error while updating the lock file of flake 'github:DeterminateSystems `src/pages/start/3.nix-develop.mdx`

### ISSUE THREAD

**Issue by 1oglop1** [DeterminateSystems/zero-to-nix#289]
Hi, it's my 2nd day learning about nix.
Quite honestly the nix space feels really daunting with the amount of overwhelming information and contradictions in docs etc..

I was hoping this project would be a great start for complete newbies like myself.

However on the page 3 I was supposed to run the command `nix develop "github:DeterminateSystems/zero-to-nix#example"`
but the result was 

```
error:
       … while updating the lock file of flake 'github:DeterminateSystems/zero-to-nix/33bf4aa4e8dd22db397eadb7955c184697996706'

       error: unsupported tarball input attribute 'rev'
       
```

MacOS nix version `nix-2.16.1`

**Comment by grahamc** [comment]
Uh oh! Unfortunately nix 2.17 has new attributes in the lock file that
has backwards compatibility issues. If you upgrade nix to 2.17, it
should fix it. You can do it like this:

sudo nix upgrade-nix --nix-store-paths-url
https://releases.nixos.org/nix/nix-2.17.0/fallback-paths.nix

Here’s more info: https://flakehub.com/docs#i-got-error-unsupported-
tarball-input-attribute-rev-what-does-this-error-mean

On September 10, 2023, GitHub ***@***.***> wrote:
> Hi, it's my 2nd day learning about nix.
>  Quite honestly the nix space feels really daunting with the amount of
> overwhelming information and contradictions in docs etc..
>
> I was hoping this project would be a great start for complete newbies
> like myself.
>
> However on the page 3 I was supposed to run the command nix develop
> "github:DeterminateSystems/zero-to-nix#example"
>  but the result was
>
> error: … while updating the lock file of flake
> 'github:DeterminateSystems/zero-to-
> nix/33bf4aa4e8dd22db397eadb7955c184697996706' error: unsupported
> tarball input attribute 'rev'
> MacOS nix version nix-2.16.1
>

—
Reply to this email directly, view it on GitHub
<https://github.com/DeterminateSystems/zero-to-nix/issues/289>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAASXLFY26SHZR6PVJJTGB3XZVYUTANCNFSM6AAAAAA4SAEMKE>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by 1oglop1** [comment]
I suspect some MacOS system update broke nix, I did reinstall using the script from this project and the command started to work 🤷

**Comment by grahamc** [comment]
Ack! I’ll take a look. I’m glad the uninstall / reinstall got it done,
but we’ll also research the upgrade problem. If you have any examples
those would be helpful :). 

On September 10, 2023, GitHub ***@***.***> wrote:
> I suspect some MacOS system update broke nix, I did reinstall using
> the script from this project and the command started to work 🤷
>

—
Reply to this email directly, view it on GitHub
<https://github.com/DeterminateSystems/zero-to-
nix/issues/289#issuecomment-1712763687>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAASXLG634I2QSQ4P3OUDGTXZWBMRANCNFSM6AAAAAA4SAEMKE>.
You are receiving this because you commented.Message ID:
***@***.***>

**Comment by 1oglop1** [comment]
I suspect it may have to do something with any of these issues:
* https://github.com/NixOS/nix/issues/3616
* https://github.com/NixOS/nix/issues/2780
* https://github.com/NixOS/nix/issues/5498

I went through the "normal" upgrade process 

```
sudo -i sh -c 'nix-channel --update && nix-env --install --attr nixpkgs.nix && launchctl remove org.nixos.nix-daemon && launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist'

```
And it finished like this
```
unpacking channels...
....
building '/nix/store/0hr1jcjmllynliknqyd28ydxvfk4v3w4-user-environment.drv'...
/Library/LaunchDaemons/org.nixos.nix-daemon.plist: service already loaded
Load failed: 37: Operation already in progress

➜  ~/projects/rust_things/tmp nix --version
nix (Nix) 2.17.0
```
